"""Optional tags on generated files (Title = TXT name, Comment = generator)."""
from __future__ import annotations

import logging
from pathlib import Path

from app.version import APP_NAME

log = logging.getLogger("audio.metadata")


def write_tags(path: Path, title: str, fmt: str) -> None:
    """Tag a freshly generated file. Existing tags are never replaced."""
    comment = f"Generated by {APP_NAME}"
    try:
        if fmt == "mp3":
            from mutagen.id3 import COMM, ID3, ID3NoHeaderError, TIT2

            try:
                tags = ID3(str(path))
            except ID3NoHeaderError:
                tags = ID3()
            if not tags.getall("TIT2"):
                tags.add(TIT2(encoding=3, text=title))
            if not tags.getall("COMM"):
                tags.add(COMM(encoding=3, lang="eng", desc="", text=comment))
            tags.save(str(path))
        elif fmt == "flac":
            from mutagen.flac import FLAC

            audio = FLAC(str(path))
            if "title" not in audio:
                audio["title"] = title
            if "comment" not in audio:
                audio["comment"] = comment
            audio.save()
    except ImportError:
        log.info("mutagen not installed – skipping metadata")
    except Exception as e:  # tagging must never fail a job
        log.warning("Could not write metadata to %s: %s", path, e)
